from skar.examples.ice_cream_conjoint import run_ice_cream
from skar.examples.charness_rabin import run_experiment_charness_rabin
from skar.examples.charness_rabin_IO import run_experiment_charness_rabin_IO
from skar.examples.charness_rabin_survey import run_experiment_charness_rabin as run_experiment_charness_rabin_survey
from skar.examples.charness_rabin_survey_writedata import run_experiment_charness_rabin as run_experiment_charness_rabin_survey_writedata
from skar.examples.charness_rabin_survey_json import run_experiment_charness_rabin as run_experiment_charness_rabin_survey_json
from skar.examples.kahneman import run_experiment_kkt
from skar.examples.samuelson_zeckhauser import run_experiment_samuelson_zeckhauser

# run_experiment_charness_rabin()
# run_experiment_charness_rabin_IO()
# run_experiment_charness_rabin_survey()
# run_experiment_charness_rabin_survey_writedata()
run_experiment_charness_rabin_survey_json()
# run_experiment_kkt()
# run_experiment_samuelson_zeckhauser()
# run_ice_cream()
